# Generated by Django 4.2 on 2023-05-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the book imprint', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprrint',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.ForeignKey(help_text='Enter the imprint for this book.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.imprint'),
        ),
    ]
